### ISSUE TITLE
服务提供者是否可以将AppHub作为公共仓库，转提供给用户使用？

### ISSUE THREAD

**Issue by wiwyhaohao** [cloudnativeapp/charts#109]
请问我作为服务提供者，是否可以将AppHub作为公共仓库，提供给我的用户使用呢？

**Comment by wonderflow** [comment]
以什么形式呢？
/cc @grumpyAmber

**Comment by wiwyhaohao** [comment]
就像rancher一样，提供一个我们自己的Portal给用户使用，在Portal上添加APPHub添加为公共仓库。我的用户登录了我的Portal，就可以看到APPHub里的Chart，然后进行部署

**Comment by grumpyAmber** [comment]
欢迎联系tunan.wr@alibaba-inc.com或者微信：dig_403详细聊下。
