### ISSUE TITLE
tekton chart 中 gcr-dashboard image 找不到

### ISSUE THREAD

**Issue by vincent178** [cloudnativeapp/charts#110]
tekton chart中使用的 registry.cn-hangzhou.aliyuncs.com/kubeapps/gcr-dashboard:latest image找不到，导致这个组件安装失败

**Comment by wonderflow** [comment]
ping @BH4AWS

**Comment by BH4AWS** [comment]
收到，我先排查看一下

**Comment by BH4AWS** [comment]
镜像缺失问题已经解决，有问题直接联系我。@vincent178

**Comment by vincent178** [comment]
好的，谢谢
