### ISSUE TITLE
Jenkins charts 中镜像的默认值不是官方的地址

### ISSUE THREAD

**Issue by LinuxSuRen** [cloudnativeapp/charts#124]
当前仓库中的默认值为 `bitnami/jenkins`
官方的镜像为 `jenkins/jenkins:lts`
不知道是否有其他原因？以及是否可以提交PR来修改。

**Comment by wonderflow** [comment]
可以提交PR修改，我们最开始是直接从bitnami中同步过来的，欢迎提交PR

**Comment by LinuxSuRen** [comment]
https://github.com/helm/charts/tree/master/stable/jenkins 这个仓库更加符合官方的风格
bitnami 做了一些他们的定制
那您的建议是直接替换呢，还只是修改镜像。我的理解是，如果当前仓库中 Jenkins 的下载量不是很多的话，就可以考虑直接替换。但是，我这边并没有相关数据。
另外，后续，chart有任何变动，我们这边的策略是人工同步呢还是有其他文档记录。

**Comment by LinuxSuRen** [comment]
@wonderflow 麻烦请教下，如果我提交到 `submitted` 这个目录的话，该如何使用呢？
我的搜索结果如下：
```
# helm repo add apphub https://apphub.aliyuncs.com
# helm search apphub/jenkins
NAME                   	CHART VERSION	APP VERSION	DESCRIPTION
apphub/jenkins         	4.1.5        	2.204.2    	The leading open source automation server
apphub/jenkins-operator	0.3.0        	0.3.0      	A Helm chart for Kubernetes Jenkins Operator
```

**Comment by wonderflow** [comment]
会出现先 experimental 库里：
`helm repo add experimental https://apphub.aliyuncs.com/experimental`

会周期性同步，同步好后可以搜到

**Comment by LinuxSuRen** [comment]
好的，感谢回复
