### ISSUE TITLE
缓存不好用

### ISSUE THREAD

**Issue by chinafzy** [cloudnativeapp/charts#133]
我设置了俩个repo，
```
NAME                	URL
stable              	https://apphub.aliyuncs.com/stable
apphub                  https://apphub.aliyuncs.com
```
拿traefik做测试，发现这些问题：
+ 俩个不一致：
  + 通过stable下载，默认latest版本是`1.87.2`，这个跟官网一致，
  + 通过apphub下载，不指定版本，默认latest版本是`1.86.1`
+ apphub下载，指定更新的版本，也是找不到，应该没来得及刷新缓存
+ 历史版本找不到，比如`1.86.0`

请加快修复哈，国内的程序员太可怜了！
谢谢了！！！

**Comment by wonderflow** [comment]
现在统一使用 `stable              	https://apphub.aliyuncs.com/stable` 这种模式了哈，`https://apphub.aliyuncs.com` 这个之所以保留是为了兼容老的，现在页面上都是只显示 `https://apphub.aliyuncs.com/stable` 这种了哈。
