### ISSUE TITLE
the served apphub service is not working

### ISSUE THREAD

**Issue by fanglijun** [cloudnativeapp/charts#139]
Which chart (use relative path, e.g. curated/airflow): 

Helm version (e.g. 3.2.0):

Cloud Provider/Platform (e.g. 阿里云):

What do you use AppHub for: (some options: internal DevOps platform, SaaS products, personal use)

How do you find AppHub: (some options: search engine, social media 头条/微信公众号/博客, word of mouth)

**Describe the bug and reproduce steps**

**What happened**

**What you expected to happen**

**Relevant screenshots**

**Anything else we need to know**:

**Comment by wonderflow** [comment]
什么挂了？

**Comment by fanglijun** [comment]
> 什么挂了？

1，https://apphub.aliyuncs.com 这个打不开了啊。

2，官网显示HUB升级中？  https://developer.aliyun.com/special/hub/notice

3，执行update报错：
helm repo update                                        

@wonderflow 

Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "apphub" chart repository (https://apphub.aliyuncs.com):
	error converting YAML to JSON: yaml: line 27: mapping values are not allowed in this context

**Comment by wonderflow** [comment]
@fanglijun  多谢反馈，由于 helm的charts 已经不是集中化存储的（https://github.com/helm/charts），所以之前helm官方仓库中大多数charts已经不再维护且不可用，开发者中心提供的免费chart服务基于中心化的官方chart同步而来，已经暂时下线。欢迎使用helm官方的chart 仓看 https://artifacthub.io/

**Comment by wonderflow** [comment]
本 repo 中的chart 已经通过github pages 托管 https://cloudnativeapp.github.io/charts/ 可以继续使用哈

**Comment by wonderflow** [comment]
https://apphub.aliyuncs.com  这个repo暂时恢复了，但是建议不要依赖哈
