### ISSUE TITLE
Wordpress couldn't be deployed by the command in README through helm

### ISSUE THREAD

**Issue by zzxwill** [cloudnativeapp/charts#22]
As `*We strongly recommend* you to use Helm v3`, some Chart installation commands are still work with Helm v2 like `Wordpress`:
```
$ helm install --name my-release \
  --set wordpressUsername=admin,wordpressPassword=password,mariadb.mariadbRootPassword=secretpassword \
    stable/wordpress
```
In `Helm V3`, it should be 
```
$ helm install my-release \
  --set wordpressUsername=admin,wordpressPassword=password,mariadb.mariadbRootPassword=secretpassword \
    stable/wordpress
```

So if we use v3 as the baseline version of Helm, we also need to make modifications to these Charts, which might not be a good idea as we don't `own` those Charts.

Then I think we need to make it more clear in REAME.md and README_en.md.

**Comment by hongchaodeng** [comment]
We will consider modifying the README in batch once Helm v3 becomes mainstream

**Comment by zzxwill** [comment]
Then I think a Helm `dry-run` command tool needs to be developed to ensure the modification is qualified.
