### ISSUE TITLE
云原生应用大赛说明

### ISSUE THREAD

**Issue by grumpyAmber** [cloudnativeapp/charts#30]
### **大赛介绍**
云原生应用，是指符合“云原生”理念的应用开发与交付模式，这是当前在云时代最受欢迎的应用开发最佳实践。
在现今的云原生生态当中，已经有很多成熟的开源软件被制作成了 Helm Charts，使得用户可以非常方便的部署使用，比如 Nginx，Apache、Elasticsearch、Redis 等等。不过，在[开放云原生应用中心 App hub（Helm Hub 中国站) ](https://developer.aliyun.com/hub)发布之前，国内用户一直都很难直接下载使用这些 Charts（原因你懂的）。而现在，AppHub 不仅为国内用户实时同步了官方 Helm Hub 里的所有应用，还自动替换了这些 Charts 里所有不可访问的镜像 URL（比如 gcr.io, quay.io 等），终于使得国内开发者通过 helm install “一键安装”应用成为了可能。
而云原生应用开发大赛，旨在鼓励和普及 Helm Charts 在国内的使用，帮助国内开发者通过云原生的方式打包和分发自己的应用，从而更好的借助云原生的浪潮，让自己的软件在云时代发挥出最大的能量！

第一季云原生应用大赛地址将于7月22日 10:00 公布
关于大赛有任何疑问，欢迎大家可以进入这个[钉钉群](https://wx.dingtalk.com/invite-page/weixin.html?corpId=dingec8ec94d58f5cdf735c2f4657eb6378f&inviterUid=2D6EDA805D98F7106B2F679C0AD92F4C&encodeDeptId=3DFDDF3655DF64E099372A3FA1525DE6)讨论进行讨论

### **如何参赛**
1.参赛者可以使用任意语言开发一个可以被容器化、运行在 K8s 上的应用；
2.然后把该应用做成 Helm Charts 格式；
3.以 Pull Request 的方式提交到 [App Hub Charts ](https://github.com/cloudnativeapp/charts)仓库，PR 提交在 submitted 文件夹下；
4.经评委审核通过后，PR 合并，Charts 会自动在 App Hub 页面上出现，即视为成功参赛。

### **大赛流程**
7月22日 开放提交
8月5日 开放 Github 点赞
8月22日 截止提交并锁定 Github 点赞榜单
8月23日 公布评委选择奖

### **参赛要求**
1.K8s 集群版本是 1.12 或者 1.14 ，Helm 版本必须是 V3。

2.参赛者提交的 PR 格式请参考这个 [PR 模板](https://github.com/cloudnativeapp/charts/pull/29)。

3.Helm Charts 的实用性、原创性、有效性说明：
【实用性】
1.应用本身的内容和功能不限，但必须是开源代码；
2.可以将业内主流的开源软件制作成 Charts 应用（但必须遵守“原创性”）；也可以是自己开发的应用（默认按App Hub的协议开源）。

【原创性】
1.参赛者上传的应用不得跟 App Hub 已经存在的应用重复；
2.如果是在已有的应用基础上进行修改，评委将有权利对原创性做出评判。
评判标准举例：
直接提交一个 guestbook： AppHub 中已经存在，重复
对 guestbook 首页文字进行改动：改动意义有限，重复
将 guestbook 的数据库从 Redis 替换成 MySQL：改动意义有限，重复
对 guestbook 进行具有实际意义的改动，比如用 NodeJS 重新实现，变成了 guestbook-node：不重复
如果两个参赛者提交了雷同的 Helm Charts，以提交 PR 时间评判，后提交的判作重复

【有效性】
1.参赛者必须在 README 里给出详细基于[Minikube 中国版](https://github.com/AliyunContainerService/minikube)的验证步骤和预期效果，请参考这个[ README 模板](https://github.com/cloudnativeapp/charts/pull/29/files#diff-7f562ee3e563f5ffd29d5a8c028da332)。对于需要多节点的应用，则必须提供基于 Kubernetes 集群的验证步骤和预期效果；
2.README 中必须给出应用的源码 URL（已经存在的开源软件或自己开发的应用均可）

注意事项：
1.评委将根据 README 里的描述，使用 [ACK（阿里云 Kubernetes 服务](https://cn.aliyun.com/product/kubernetes)）或者[Minikube 中国版](https://github.com/AliyunContainerService/minikube)中国版来验证预期效果；
2.只有在大赛管理员在验证审核应用通过后，合并 PR，才视为成功参赛，无法验证效果的 Helm Charts 将被视为无效参赛；
3.为了保证 Charts 可被验证，请尽量减少 Charts 中跟云产品强耦合的部分（比如：云盘类型的 Persistent Volume）。如果无法避免，请定义成 Charts 参数以便评委进行替换验证；或者直接基于 ACK 进行 Charts 制作（推荐）。

### **奖项说明**
**最受欢迎奖🏅**
最受欢迎奖完全是由大众评选出来的，此奖项榜单（大众榜单）完全由参赛者提交的 PR 的点赞数来排名。
榜单 50 人，排名第一的参赛者将获得：Cherry 键盘，排名 2-10 的参赛者将获得：天猫精灵，排名 11-50 的参赛者将获得：阿里云T恤
**评委选择奖🏅**
评委选择奖将由4位云原生领域专家，从 charts 的原创性、实用性、创新性等三个维度来评选，评委选择奖仅一位名额，奖品是苹果 AirPods，将从大众榜单的前 50 名中产生。

### **FAQ**
Q：我作为参赛者能够上传多个 charts 吗？大众榜单的排名最后会把我们多个 charts 的点赞数相加吗？
A：参赛者可以提交多个 charts。但是大众榜单是根据您单个 chart 的点赞数来排名的。
举个例子，如果您上传了 2 个 charts，分别排名第2和第13，您将获得两份相应的奖品。

**Comment by buaa-zzxwill** [comment]
请问，`开放 Github 点赞` 具体怎么点赞？

**Comment by wonderflow** [comment]
https://developer.aliyun.com/special/apphubchallenge?spm=a2c6h.12873679.0.0.74501107jTMjNS

比赛已经结束，关闭issue
