### ISSUE TITLE
[Help wanted] 添加维护者到chart

### ISSUE THREAD

**Issue by Aisuko** [cloudnativeapp/charts#82]
各位好，非常感谢各位花费精力提供了这个很棒的项目，推广了helm/charts的使用。

1，我是@helm/charts 的incubator/mysqlha 和stable/influxdb的owner，负责日常维护helm/charts 。如果这两个chats需要维护者或者有bug可以通知到我。

2， 相信大家都看到了 @helm/charts PR#6095 我也觉得这是去中心化是一个很棒的主意。

3，最后yaml文件都应该被框架生成而不需要人工去写。

**Comment by wonderflow** [comment]
你说的添加维护者是指 `chart.yaml` 里的 `maintainers ` 字段吗？

**Comment by Aisuko** [comment]
@wonderflow 您好，我目前了解的是@helm/charts 的做法，OWNERS 文件+上面提到的`maintainers`字段，在合并PR的流程中，首先分给OWNER review，然后kubernetes/test-infra根据指令执行最后合并。这个具体看cloudnativeapp想怎么制定规则。

**Comment by wonderflow** [comment]
好建议，多谢，我们后续会考虑加上
