### ISSUE TITLE
gitea chart 修改建议

### ISSUE THREAD

**Issue by jinliang123** [cloudnativeapp/charts#99]
貌似这里有点小问题，如果 `--set expose.clusterIP.ports.http=3000 ` ， ingress 方式就无法访问了
https://github.com/cloudnativeapp/charts/blob/360955d640b24bafc4a0ee8eecad97ac457d9a70/submitted/gitea/templates/ingress.yaml#L22

https://github.com/cloudnativeapp/charts/blob/360955d640b24bafc4a0ee8eecad97ac457d9a70/submitted/gitea/templates/service.yaml#L20

这一行不需要删除吗？
https://github.com/cloudnativeapp/charts/blob/360955d640b24bafc4a0ee8eecad97ac457d9a70/submitted/gitea/values.yaml#L68

ping @hongchaodeng @zeusro

**Comment by hongchaodeng** [comment]
@jinliang123 交个修复 PR ？

**Comment by wonderflow** [comment]
fixed by https://github.com/cloudnativeapp/charts/pull/104
